name: WSO2 MI CI

on:
  push:
    branches:
      - main
  pull_request:
  



permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Set up JDK & Maven
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # 3. Build CAR
      - name: Build CAR
        run: mvn clean package

      - name: CAR File Location
        run: |
          echo "Listing target directory:"
          ls -la ${{ github.workspace }}/target/
          echo "Searching for CAR file:"
          find ${{ github.workspace }} -type f -name "*.car"
          CAR_FILE=$(find ${{ github.workspace }} -type f -name "*.car" | head -n 1)
          if [ -z "$CAR_FILE" ]; then
            echo "Error: No CAR file found"
            exit 1
          fi
          echo "CAR file found: $CAR_FILE"
          echo "Copying CAR file to deployment/docker/CompositeApps/"
          mkdir -p deployment/docker/CompositeApps
          cp "$CAR_FILE" deployment/docker/CompositeApps/
          ls -la deployment/docker/CompositeApps/
