name: Building CAR File

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Set up JDK & Maven
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # 3. Build CAR
      - name: Build CAR
        run: mvn clean package
        # Assumes pom.xml is in root; add working-directory if in a subdirectory

      # 4. Locate and copy CAR file
      - name: CAR File Location
        run: |
          echo "Listing target directory:"
          ls -la ${{ github.workspace }}/target/
          echo "Searching for CAR file:"
          find ${{ github.workspace }} -type f -name "*.car"
          CAR_FILE=$(find ${{ github.workspace }} -type f -name "*.car" | head -n 1)
          if [ -z "$CAR_FILE" ]; then
            echo "Error: No CAR file found"
            exit 1
          fi
          echo "CAR file found: $CAR_FILE"
          echo "Checking CAR file contents:"
          unzip -l "$CAR_FILE"
          echo "Copying CAR file to deployment/docker/CompositeApps/"
          mkdir -p ${{ github.workspace }}/deployment/docker/CompositeApps
          cp "$CAR_FILE" ${{ github.workspace }}/deployment/docker/CompositeApps/
          ls -la ${{ github.workspace }}/deployment/docker/CompositeApps/

      # 5. Build Docker Image
      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t helloworldservice:1.0.0 -f Dockerfile .
          echo "Listing built images:"
          docker images | grep helloworldservice

      # 6. Test CAR File in Custom Image
      - name: Test CAR File in Custom Image
        run: |
          echo "Running custom Docker image..."
          docker run -d --name wso2mi -p 8290:8290 -p 9164:9164 helloworldservice:1.0.0
          echo "Waiting for WSO2 MI server to start and deploy CAR..."
          sleep 120
          echo "Checking carbonapps directory in container..."
          docker exec wso2mi ls -la /home/wso2carbon/wso2mi/repository/deployment/server/carbonapps
          echo "Checking file permissions in container..."
          docker exec wso2mi stat /home/wso2carbon/wso2mi/repository/deployment/server/carbonapps/*.car
          echo "Checking server logs..."
          docker logs wso2mi
          echo "Checking CAR deployment..."
          docker logs wso2mi | grep "Deploying Carbon Application" || echo "No deployment message found"
          echo "Checking for deployment errors..."
          docker logs wso2mi | grep -i "error" || echo "No error messages found"
          echo "Checking available APIs..."
          curl -k --retry 5 --retry-delay 5 --retry-max-time 60 https://localhost:9164/management/apis || echo "Failed to list APIs"
          echo "Testing API endpoint..."
          curl --retry 10 --retry-delay 5 --retry-max-time 120 -f http://localhost:8290/HelloWorld || {
            echo "Error: API test failed"
            exit 1
          }
          echo "API response:"
          curl http://localhost:8290/HelloWorld
          docker stop wso2mi
          docker rm wso2mi

      # 6. Upload CAR artifact
      - name: Upload CAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: car-artifact
          path: target/*.car
          retention-days: 7