name: Stop WSO2 MI Deployment on Minikube

on:
  workflow_dispatch:  # Manual trigger via GitHub UI or API

permissions:
  contents: read

jobs:
  stop:
    runs-on: self-hosted  # Assumes Minikube is running on a self-hosted runner

    steps:
      # 1. Debug Runner Environment
      - name: Debug Runner Environment
        run: |
          echo "Runner OS:"
          uname -a
          echo "Minikube status:"
          minikube status || { echo "Minikube is not running"; exit 1; }
          echo "kubectl version:"
          kubectl version --client
          echo "kubectl cluster info:"
          kubectl cluster-info

      # 2. Delete Deployment and Service
      - name: Delete WSO2 MI Deployment and Service
        run: |
          echo "Deleting Kubernetes resources..."
          kubectl delete deployment wso2mi-deployment || echo "Deployment not found"
          kubectl delete service wso2mi-service || echo "Service not found"
          echo "Listing remaining pods:"
          kubectl get pods -o wide || echo "No pods found"

      # 3. Optional: Stop Minikube
      - name: Stop Minikube
        run: |
          echo "Stopping Minikube..."
          minikube stop || echo "Minikube stop failed or already stopped"
          echo "Minikube status:"
          minikube status || echo "Minikube is not running"

      # 4. Upload Logs
      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: stop-logs
          path: |
            stop_logs.txt
          retention-days: 7