name: Deploy WSO2 MI to Minikube

on:
  workflow_dispatch:  # Manual trigger via GitHub UI or API

permissions:
  contents: read
  packages: write

env:
  DOCKER_IMAGE_TAG: helloworldservice:1.0.0
  WSO2_SERVER_HOME: /home/wso2carbon/wso2mi-4.4.0

jobs:
  deploy:
    runs-on: self-hosted  # Assumes Minikube is running on a self-hosted runner

    steps:
      # 1. Debug Runner Environment
      - name: Debug Runner Environment
        run: |
          echo "Runner OS:"
          uname -a
          echo "Disk space:"
          df -h
          echo "Environment variables:"
          env
          echo "Current directory:"
          pwd
          echo "Minikube status:"
          minikube status || { echo "Minikube is not running"; exit 1; }
          echo "kubectl version:"
          kubectl version --client
          echo "kubectl cluster info:"
          kubectl cluster-info

      # 2. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4
      

      # 3. Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Debug Java and Maven
        run: |
          echo "Java version:"
          java -version
          echo "Maven version:"
          mvn --version

      # 4. Build CAR File
      - name: Build CAR File
        run: |
          echo "Building CAR file..."
          mvn clean package -X || { echo "Maven build failed"; exit 1; }
          echo "Listing target directory:"
          ls -la ${{ github.workspace }}/target/
          CAR_FILE=$(find ${{ github.workspace }}/target -type f -name "*.car" | head -n 1)
          if [ -z "$CAR_FILE" ]; then
            echo "Error: No CAR file found"
            exit 1
          fi
          echo "CAR file found: $CAR_FILE"
          echo "Checking CAR file contents:"
          unzip -l "$CAR_FILE"

      # 5. Copy CAR File
      - name: Copy CAR File
        run: |
          echo "Copying CAR file to deployment/docker/CompositeApps/"
          mkdir -p ${{ github.workspace }}/deployment/docker/CompositeApps
          cp ${{ github.workspace }}/target/*.car ${{ github.workspace }}/deployment/docker/CompositeApps/
          ls -la ${{ github.workspace }}/deployment/docker/CompositeApps/

      # 6. Build Docker Image
      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t ${{ env.DOCKER_IMAGE_TAG }} -f ${{ github.workspace }}/deployment/docker/Dockerfile ${{ github.workspace }} || { echo "Docker build failed"; exit 1; }
          echo "Listing built images:"
          docker images | grep helloworldservice

      # 7. Test Docker Run on Minikube
      - name: Test Docker Run on Minikube
        run: |
          echo "Configuring Docker to use Minikube's Docker daemon..."
          eval $(minikube docker-env)
          echo "Running Docker container on Minikube's Docker daemon..."
          docker run -d --name test-wso2mi -p 8290:8290 -p 9164:9164 ${{ env.DOCKER_IMAGE_TAG }} || { echo "Docker run failed"; exit 1; }
          echo "Waiting for container to be ready..."
          sleep 10
          echo "Checking container status..."
          docker ps | grep test-wso2mi
          echo "Checking container logs..."
          docker logs test-wso2mi > docker_logs.txt
          cat docker_logs.txt
          echo "Checking for errors in logs..."
          grep -i "error" docker_logs.txt || echo "No errors found in Docker logs"
          echo "Stopping and removing test container..."
          docker stop test-wso2mi
          docker rm test-wso2mi

      # 8. Load Docker Image into Minikube
      - name: Load Docker Image to Minikube
        run: |
          echo "Configuring Docker to use Minikube's Docker daemon..."
          eval $(minikube docker-env)
          echo "Loading Docker image into Minikube..."
          minikube image load ${{ env.DOCKER_IMAGE_TAG }} || { echo "Image load failed"; exit 1; }
          echo "Listing Minikube images:"
          minikube image ls | grep helloworldservice

      # 9. Deploy to Minikube
      - name: Deploy to Minikube
        run: |
          echo "Applying Kubernetes manifests..."
          cat <<EOF | kubectl apply -f -
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: wso2mi-deployment
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: wso2mi
            template:
              metadata:
                labels:
                  app: wso2mi
              spec:
                containers:
                - name: wso2mi
                  image: ${{ env.DOCKER_IMAGE_TAG }}
                  imagePullPolicy: Never
                  ports:
                  - containerPort: 8290
                  - containerPort: 9164
                  env:
                  - name: WSO2_SERVER_HOME
                    value: "${{ env.WSO2_SERVER_HOME }}"
                  readinessProbe:
                    httpGet:
                      path: /management/health
                      port: 9164
                      scheme: HTTPS
                    initialDelaySeconds: 40
                    periodSeconds: 10
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: wso2mi-service
          spec:
            selector:
              app: wso2mi
            ports:
            - name: http
              port: 8290
              targetPort: 8290
            - name: https
              port: 9164
              targetPort: 9164
            type: ClusterIP
          EOF
          echo "Listing pods:"
          kubectl get pods -o wide || echo "Failed to list pods"
